[project]
name = "quotes-forever"
version = "0.1.0"
description = ""
dependencies = [
    "streamlit>=1.28.0",
    "requests",
    
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
